import unittest

from MathProtEnergyProcBase.tests.TestNonEqBase import TestNonEqSystemBase
from MathProtEnergyProcBase.tests.TestNonEqQBase import TestNonEqSystemQBase
from MathProtEnergyProcBase.tests.TestPosLinearFilter import TestPosLinearFilter
from MathProtEnergyProcBase.tests.TestExpFilter import TestExpFilter
from MathProtEnergyProcBase.tests.TestKineticMatrixFromPosSubMatrix import TestKineticMatrixFromPosSubMatrix
from MathProtEnergyProcBase.tests.TestKineticMatrixFromSymAsym import TestKineticMatrixFromSymAsym
from MathProtEnergyProcBase.tests.TestReluFilter import TestReluFilter
from MathProtEnergyProcBase.tests.TestSymRevMatrix import TestSymRevMatrix
from MathProtEnergyProcBase.tests.TestSymAndAsymRevMatrix import TestSymAndAsymRevMatrix
from MathProtEnergyProcBase.tests.TestKineticMatrixFromFacStreamEkvAff import TestKineticMatrixFromFacStreamEkvAff
from MathProtEnergyProcBase.tests.TestKineticMarix import TestKineticMarix
from MathProtEnergyProcBase.tests.TestKineticMarixQ import TestKineticMarixQ
from MathProtEnergyProcBase.tests.TestBetaProcess import TestBetaProcess
from MathProtEnergyProcBase.tests.TestBetaMatrix import TestBetaMatrix
from MathProtEnergyProcBase.tests.TestIntPotentialFromCompFun import TestIntPotentialFromCompFun
from MathProtEnergyProcBase.tests.TestTemperaturesFun import TestTemperaturesFun
from MathProtEnergyProcBase.tests.TestJacSStateCoordinatesFunT import TestJacSStateCoordinatesFunT
from MathProtEnergyProcBase.tests.TestJacSStateCoordinatesFunSdU import TestJacSStateCoordinatesFunSdU
from MathProtEnergyProcBase.tests.TestJacSStateCoordinatesIndepenCompFunT import TestJacSStateCoordinatesIndepenCompFunT
from MathProtEnergyProcBase.tests.TestJacSStateCoordinatesIndepenCompFunSdU import TestJacSStateCoordinatesIndepenCompFunSdU
from MathProtEnergyProcBase.tests.TestIntPotentialFunTOne import TestIntPotentialFunTOne
from MathProtEnergyProcBase.tests.TestIntPotentialFunSdUOne import TestIntPotentialFunSdUOne
from MathProtEnergyProcBase.tests.TestInvHeatCapacityHeatEffectsFun import TestInvHeatCapacityHeatEffectsFun
from MathProtEnergyProcBase.tests.TestInvHeatCapacityHeatEffectsOneFun import TestInvHeatCapacityHeatEffectsOneFun
from MathProtEnergyProcBase.tests.TestHeatEffectsFun import TestHeatEffectsFun
from MathProtEnergyProcBase.tests.TestHeatCapacitiesFun import TestHeatCapacitiesFun
from MathProtEnergyProcBase.tests.TestHeatCapacitiesOneFun import TestHeatCapacitiesOneFun
from MathProtEnergyProcBase.tests.TestIntPotentialFunT import TestIntPotentialFunT
from MathProtEnergyProcBase.tests.TestIntPotentialFunSdU import TestIntPotentialFunSdU
from MathProtEnergyProcBase.tests.TestIntPotentialBaseCompFunT import TestIntPotentialBaseCompFunT
from MathProtEnergyProcBase.tests.TestIntPotentialBaseCompFunSdU import TestIntPotentialBaseCompFunSdU
from MathProtEnergyProcBase.tests.TestIntPotentialIndepenCompFunT import TestIntPotentialIndepenCompFunT
from MathProtEnergyProcBase.tests.TestIntPotentialIndepenCompFunSdU import TestIntPotentialIndepenCompFunSdU
from MathProtEnergyProcBase.tests.TestIntPotentialsBase import TestIntPotentialsBase
from MathProtEnergyProcBase.tests.TestIntPotentialsOne import TestIntPotentialsOne
from MathProtEnergyProcBase.tests.TestHeatValues import TestHeatValues
from MathProtEnergyProcBase.tests.TestHeatValuesOne import TestHeatValuesOne
from MathProtEnergyProcBase.tests.TestHeatPowerValuesConcat import TestHeatPowerValuesConcat
from MathProtEnergyProcBase.tests.TestHeatPowerValuesConcatSelect import TestHeatPowerValuesConcatSelect

# Запустить тестирование
if __name__ == "__main__":
    unittest.main()
